### PR TITLE
add more tests

### PR DESCRIPTION
**Pull request by yrunts**
@Bodyk1Love Looks good.
Please find more tests and try to adapt the code to pass them.

What is the complexity of the algorithm? 
Why for each word algorithm checks is language English?
Why we create dict with roman numbers in each convert function call?
How much time do we need to convert several pages from a historical book?
Maybe python module `re` or str.replace() could help to convert move efficiently?

### CODE REVIEW

**Comment by bbary00** [comment]
1) I will make one global variable with the dict
2) Algorithm must check English language only at the beginning. I'll fix
3) After fixing I'll check time.
4) Can you tell me more about .replace function?
    You want me to fix this line of code?
       text[text.index(word)] = str(roman_pairs[word])

**Comment by yrunts** [comment]
> 1. I will make one global variable with the dict
> 2. Algorithm must check English language only at the beginning. I'll fix
> 3. After fixing I'll check time.
> 4. Can you tell me more about .replace function?
>    You want me to fix this line of code?
>    text[text.index(word)] = str(roman_pairs[word])

https://docs.python.org/3.6/library/stdtypes.html#string-methods
https://docs.python.org/3/library/re.html#re.sub

**Comment by bbary00** [comment]
One more question.
Do we really need to check roman numbers in English language?
Because  I've explored that all centuries in English are written like that : "6th century" or "fifth century"

**Comment by yrunts** [comment]
Ok, maybe it is not mandatory. So if a text is not in Ukrainian just return original text.

**Pull request closed without merging**
